# Generated by Django 4.0.2 on 2022-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.IntegerField(verbose_name='Dates')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('responsibilities', models.CharField(max_length=255, verbose_name='Responsibilities')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
            },
        ),
    ]
