# Generated by Django 4.0.2 on 2022-11-10 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='dates',
        ),
        migrations.AddField(
            model_name='experience',
            name='date_end',
            field=models.DateField(default=datetime.date.today, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Start date'),
        ),
    ]
