# Generated by Django 4.0.2 on 2022-11-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_remove_experience_dates_experience_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='stack',
            field=models.CharField(default='Python', max_length=255, verbose_name='Stack'),
        ),
    ]
