# Generated by Django 4.0.2 on 2022-11-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagehead',
            options={'verbose_name': 'My foto', 'verbose_name_plural': 'My fotos'},
        ),
    ]
