# Generated by Django 4.0.2 on 2022-11-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_imagehead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagehead',
            options={'verbose_name': 'Head photo', 'verbose_name_plural': 'Head photos'},
        ),
    ]
