# Generated by Django 4.0.2 on 2022-10-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.IntegerField(max_length=255, verbose_name='Level'),
        ),
    ]
