# Generated by Django 4.0.2 on 2022-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.IntegerField(verbose_name='Level'),
        ),
    ]
